### PR TITLE
Add new Trigger Endpoints

### PR DESCRIPTION
**Pull request by wenga86**
# New Endpoints
`/campaigns/trigger/send` - Allows one to trigger a send to for a campaign
`/canvas/trigger/send` - Allows one to trigger a send for a canvas

### CODE REVIEW

**Comment by wenga86** [comment]
@hugobast - Hi, it appears I no longer have access to merge and cut releases for this repo. Could you possibly help me to resolve this?

**Comment by hugobast** [comment]
> @hugobast - Hi, it appears I no longer have access to merge and cut releases for this repo. Could you possibly help me to resolve this?

Seems DynamoMTL removed me from the org I can't manage this repo anymore, @nemy could you re-instate me and fix up the permission to have wenga86 be able to make releases to this repo like before?

**Comment by nemy** [comment]
> > @hugobast - Hi, it appears I no longer have access to merge and cut releases for this repo. Could you possibly help me to resolve this?
> 
> Seems DynamoMTL removed me from the org I can't manage this repo anymore, @nemy could you re-instate me and fix up the permission to have wenga86 be able to make releases to this repo like before?

Sorry @hugobast I have added you as an admin collaborator to this repo again. Let me know if you need anything else.

**Comment by hugobast** [comment]
@nemy thanks!

**Comment by wenga86** [comment]
Thanks, @nemy & @hugobast!

**Pull request merged**
